spring.application.name=evabot

spring.datasource.url=jdbc:mysql://localhost:3306/evabot_db
spring.datasource.username=evabot
spring.datasource.password=evabotM@ster

spring.flyway.locations=classpath:db/migration,classpath:db/callback