CREATE TABLE IF NOT EXISTS history_name (
	id INT NOT NULL AUTO_INCREMENT,
	creation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modification_time TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	nickname VARCHAR(255) NULL,
	
	player_id INT NOT NULL,
	
	PRIMARY KEY(id),
	CONSTRAINT FK_HistoryName_ERPlayer FOREIGN KEY (player_id) REFERENCES er_player(id)
);