CREATE TABLE IF NOT EXISTS message_log (
	id INT NOT NULL AUTO_INCREMENT,
	creation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modification_time TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	
	message VARCHAR(15000) NOT NULL,
	author_name VARCHAR(255) NOT NULL,
	scrim_id INT NOT NULL,
	
	PRIMARY KEY(id),
	CONSTRAINT FK_MessageLog_Scrim FOREIGN KEY (scrim_id) REFERENCES scrim(id)
);