CREATE TABLE IF NOT EXISTS spectator (
	id INT NOT NULL AUTO_INCREMENT,
	creation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modification_time TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	
	name VARCHAR(255) NOT NULL,
	scrim_id INT NOT NULL,
	
	PRIMARY KEY(id),
	CONSTRAINT FK_Spectator_Scrim FOREIGN KEY (scrim_id) REFERENCES scrim(id)
);