CREATE TABLE IF NOT EXISTS server (
	id INT NOT NULL AUTO_INCREMENT,
	creation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	modification_time TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	
	name VARCHAR(255) NULL,
	server_id VARCHAR(255) NOT NULL,
	
	PRIMARY KEY(id),
	CONSTRAINT UC_Server_server_id UNIQUE(server_id)
);